const name = prompt("What is name?")
console.log("Name ~",name)
const lastname = prompt("What is lastname?")
console.log("Surname ~",lastname)
const job = prompt("What do you do?")
console.log("Job ~",job)
const age = prompt("How old are you?")
console.log("Age ~",age)
const gander = prompt("What is your gander?")
console.log("Gander ~",gander)
const english = confirm("Do you speak english?")
console.log("English ~",english)